#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Policy {
    pub angle_calls: bool,
    pub angle_objects: bool,
    pub arm_bars: bool,
    pub arm_empties: bool,
    pub arm_flattens: bool,
    pub arm_guards: bool,
    pub arrow_after: &'static [&'static [u8]],
    pub arrow_bodies: bool,
    pub arrow_parens: bool,
    pub assign_groups: bool,
    pub assign_joins: bool,
    pub assign_lines: bool,
    pub assign_values: bool,
    pub assign_wraps: bool,
    pub attribute_ends: bool,
    pub attribute_joins: bool,
    pub attribute_spans: bool,
    pub attribute_width: u32,
    pub attribute_words: &'static [&'static [u8]],
    pub bar_levels: bool,
    pub binary_lines: bool,
    pub binary_parts: bool,
    pub binder_words: &'static [&'static [u8]],
    pub binding_bases: &'static [&'static [u8]],
    pub binding_codes: bool,
    pub binding_leads: bool,
    pub binding_words: &'static [&'static [&'static [u8]]],
    pub blank_edges: bool,
    pub blank_max: u32,
    pub block_chains: bool,
    pub block_joins: bool,
    pub block_leads: &'static [&'static [u8]],
    pub block_words: &'static [&'static [u8]],
    pub body_owns: bool,
    pub body_parts: bool,
    pub body_words: &'static [&'static [u8]],
    pub brace_bodies: bool,
    pub brace_continues: bool,
    pub brace_counts: bool,
    pub brace_dedents: bool,
    pub brace_hugs: bool,
    pub brace_leads: bool,
    pub brace_levels: bool,
    pub brace_pairs: bool,
    pub brace_parts: bool,
    pub brace_remarks: bool,
    pub brace_spaces: bool,
    pub brace_spans: bool,
    pub brace_words: &'static [&'static [u8]],
    pub bracket_types: bool,
    pub branch_joins: bool,
    pub branch_width: u32,
    pub branch_words: &'static [&'static [u8]],
    pub build_blocks: bool,
    pub call_budgets: bool,
    pub call_nests: bool,
    pub call_width: u32,
    pub callee_marks: &'static [&'static [u8]],
    pub callee_words: &'static [&'static [u8]],
    pub carriage_breaks: bool,
    pub cast_joins: bool,
    pub cast_words: &'static [&'static [u8]],
    pub chain_groups: bool,
    pub chain_hugs: bool,
    pub chain_joins: bool,
    pub chain_soles: bool,
    pub chain_width: u32,
    pub clause_bases: bool,
    pub clause_ends: bool,
    pub clause_lines: bool,
    pub clause_words: &'static [&'static [u8]],
    pub close_hugs: bool,
    pub colon_continues: bool,
    pub comma_adds: bool,
    pub comma_continues: bool,
    pub comma_drops: bool,
    pub comma_parts: bool,
    pub compose_parts: bool,
    pub construct_words: &'static [&'static [u8]],
    pub continue_words: &'static [&'static [u8]],
    pub convention_strings: bool,
    pub declaration_words: &'static [&'static [u8]],
    pub declare_lines: bool,
    pub declare_words: &'static [&'static [u8]],
    pub dedent_words: &'static [&'static [u8]],
    pub define_joins: bool,
    pub define_widths: bool,
    pub define_words: &'static [&'static [u8]],
    pub document_blocks: bool,
    pub else_width: u32,
    pub empty_words: &'static [&'static [u8]],
    pub end_words: &'static [&'static [u8]],
    pub field_width: u32,
    pub follow_heads: &'static [&'static [u8]],
    pub follow_words: &'static [&'static [u8]],
    pub generic_levels: bool,
    pub generic_nests: bool,
    pub generic_parts: bool,
    pub group_words: &'static [&'static [u8]],
    pub head_blocks: bool,
    pub head_stops: &'static [&'static [u8]],
    pub header_braces: bool,
    pub header_extends: bool,
    pub header_joins: bool,
    pub header_levels: bool,
    pub header_lines: bool,
    pub header_parens: bool,
    pub header_widths: bool,
    pub header_words: &'static [&'static [u8]],
    pub heritage_parts: bool,
    pub hug_braces: bool,
    pub hug_lambdas: bool,
    pub hug_lasts: bool,
    pub hug_soles: bool,
    pub hug_words: &'static [&'static [u8]],
    pub inline_layout: bool,
    pub inline_remarks: bool,
    pub item_words: &'static [&'static [u8]],
    pub key_quotes: bool,
    pub key_words: &'static [&'static [u8]],
    pub keyword_gaps: bool,
    pub label_lines: bool,
    pub label_words: &'static [&'static [u8]],
    pub lambda_flattens: bool,
    pub lead_words: &'static [&'static [u8]],
    pub level_words: &'static [&'static [u8]],
    pub lifetime_tight: bool,
    pub link_levels: bool,
    pub link_nests: bool,
    pub link_spans: bool,
    pub list_blanks: bool,
    pub list_fills: bool,
    pub list_groups: bool,
    pub list_hugs: bool,
    pub list_leads: &'static [&'static [u8]],
    pub list_mixes: u32,
    pub list_remarks: bool,
    pub list_sorts: bool,
    pub list_spreads: bool,
    pub list_tight: &'static [&'static [u8]],
    pub list_width: u32,
    pub list_words: &'static [&'static [u8]],
    pub literal_joins: bool,
    pub literal_width: u32,
    pub macro_bodies: bool,
    pub macro_defines: bool,
    pub macro_gaps: bool,
    pub macro_indents: bool,
    pub macro_spans: bool,
    pub member_words: &'static [&'static [u8]],
    pub nested_levels: bool,
    pub number_forms: bool,
    pub operand_joins: bool,
    pub operand_levels: bool,
    pub operand_words: &'static [&'static [u8]],
    pub operator_words: &'static [&'static [u8]],
    pub order_words: &'static [&'static [u8]],
    pub parameter_words: &'static [&'static [u8]],
    pub pattern_frames: bool,
    pub pattern_words: &'static [&'static [u8]],
    pub postfix_words: &'static [&'static [u8]],
    pub prefix_words: &'static [&'static [u8]],
    pub printed_gaps: bool,
    pub raise_hugged: bool,
    pub remark_carries: bool,
    pub remark_dedents: bool,
    pub remark_gaps: bool,
    pub remark_leads: bool,
    pub remark_levels: bool,
    pub remark_suffix: bool,
    pub remark_tails: bool,
    pub rest_binds: bool,
    pub return_parens: bool,
    pub root_joins: bool,
    pub row_parts: bool,
    pub sentinel_colons: bool,
    pub signature_words: &'static [&'static [u8]],
    pub skip_words: &'static [&'static [u8]],
    pub slice_colons: bool,
    pub sole_hugs: bool,
    pub sole_joins: bool,
    pub source_gaps: bool,
    pub source_values: &'static [&'static [u8]],
    pub source_words: &'static [&'static [u8]],
    pub spaced_words: &'static [&'static [u8]],
    pub span_levels: bool,
    pub spec_depths: bool,
    pub special_macros: &'static [(&'static [u8], u32)],
    pub spread_blanks: bool,
    pub string_quotes: bool,
    pub template_spans: bool,
    pub template_units: bool,
    pub ternary_colon: bool,
    pub ternary_levels: bool,
    pub ternary_parts: bool,
    pub test_joins: bool,
    pub tight_from_source: &'static [&'static [u8]],
    pub tight_words: &'static [&'static [u8]],
    pub type_leads: &'static [&'static [u8]],
    pub type_words: &'static [&'static [u8]],
    pub unary_words: &'static [&'static [u8]],
    pub union_parts: bool,
    pub units: bool,
    pub value_cap: u32,
    pub value_columns: bool,
    pub value_words: &'static [&'static [u8]],
    pub variant_width: u32,
    pub verbatim_words: &'static [&'static [u8]],
    pub width_lists: bool,
}
